# -*- coding: utf-8 -*-
"""Ecommerce customers project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7EZgxATvrY9UDWwnC0zprwvzH62RCqo
"""

#IMPORTING NECESSARY LiBRARIES
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline
#to generate train and test data
import seaborn as sns
from sklearn.model_selection import train_test_split
#library to perform linear regression
from sklearn.linear_model import LinearRegression
#for performance test
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
#to remove warnings messagess
import warnings
warnings.filterwarnings('ignore')

#reading the excel file
from google.colab import files
uploaded=files.upload()
df=pd.read_excel("Ecommerce Customers.xlsx")
#setting dependent and independent variables
x=df.drop(columns=['Yearly Amount Spent','Email','Address','Avatar'])
y=df['Yearly Amount Spent']
#split the dataset into training and testing sets
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=46)
#performing lr
model=LinearRegression()
model.fit(x_train,y_train)
#results of lr
a=model.intercept_
m=model.coef_
print("intercept: ",a,"coefficient: ",m)
#evaluate test
y_predict=model.predict(x_test)
plt.scatter(y_test,y_predict)
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Actual VS Predicted")
plt.show()
#find values
print("MSE: ",mean_squared_error(y_test,y_predict))
print("R-squared: ",r2_score(y_test,y_predict))
print("MAE: ",mean_absolute_error(y_test,y_predict))
#for testing
arr=[32,11,37,4]
predicted_amount=model.predict(np.array(arr).reshape(1,-1))
print("Predicted_amount: ",predicted_amount)