# -*- coding: utf-8 -*-
"""House project week 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZU5YrSC15wFAzGSmrXeZ5RFvA0wJJxW
"""

# Commented out IPython magic to ensure Python compatibility.

#IMPORTING NECESSARY LiBRARIES
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline
#to generate train and test data
import seaborn as sns
from sklearn.model_selection import train_test_split
#library to perform linear regression
from sklearn.linear_model import LinearRegression
#for performance test
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
#to remove warnings messagess
import warnings
warnings.filterwarnings('ignore')

#READING THE CSV FILE

from google.colab import files
uploaded=files.upload()
df=pd.read_csv("Housing.csv")
#change the column in binary format
df['mainroad']=df['mainroad'].astype('category')
df['mainroad']=df['mainroad'].cat.codes
df['guestroom']=df['guestroom'].astype('category')
df['guestroom']=df['guestroom'].cat.codes
df['basement']=df['basement'].astype('category')
df['basement']=df['basement'].cat.codes
df['hotwaterheating']=df['hotwaterheating'].astype('category')
df['hotwaterheating']=df['hotwaterheating'].cat.codes
df['airconditioning']=df['airconditioning'].astype('category')
df['airconditioning']=df['airconditioning'].cat.codes
df['prefarea']=df['prefarea'].astype('category')
df['prefarea']=df['prefarea'].cat.codes
df['furnishingstatus']=df['furnishingstatus'].astype('category')
df['furnishingstatus']=df['furnishingstatus'].cat.codes
#setting independent and dependent variables and generate test

x=df.drop(columns='price')
y=df['price']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=5)
print(x_train,x_test,y_train,y_test,sep="\n")

#Performing LR
LR=LinearRegression()
LR.fit(x_train,y_train)
#Results of LR
a=LR.intercept_
m=LR.coef_
print(a,m)
#import statsmodels.api as sm

#x_test_sm=sm.add_constant(x_test)
#permoring test
y_predict=LR.predict(x_test)


plt.scatter(y_test,y_predict)
from sklearn.metrics import mean_squared_error

print("RMSE: ",np.sqrt(mean_squared_error(y_test,y_predict)))
print("R-squared: ",r2_score(y_test,y_predict))
print("MAE: ",mean_absolute_error(y_test,y_predict))
sns.pairplot(df,x_vars=['area','bathrooms','bedrooms','stories','parking'],y_vars=['price'],size=5,kind='scatter')
arr=[7420,4,2,3,1,0,0,0,1,2,1,0]
prediction=np.array(arr).reshape(1,-1)
predicted_price=LR.predict(prediction)
print("predicted price: ",predicted_price)

